server:
  port: 8099
security:
  basic:
    enabled: false

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/eims
    username: postgres
    password: admin
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
